# Generated by Django 4.1.7 on 2023-02-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decade', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Charts',
                'ordering': ['decade'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('video_link', models.CharField(max_length=100)),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.chart')),
            ],
        ),
    ]
