# Generated by Django 4.1.7 on 2023-02-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_song_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='video_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
