# Generated by Django 4.1.7 on 2023-02-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='rank',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
