# Generated by Django 4.1.7 on 2023-02-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_alter_song_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='rank',
        ),
        migrations.CreateModel(
            name='ChartSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, unique=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.chart')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.song')),
            ],
        ),
    ]
