# Generated by Django 4.1.7 on 2023-02-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_remove_song_rank_chartsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='charts.chart'),
        ),
        migrations.DeleteModel(
            name='ChartSong',
        ),
    ]
