# Generated by Django 4.1.7 on 2023-02-22 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_song_rank_alter_song_decade_delete_chartsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.chart'),
        ),
    ]
