# Generated by Django 4.1.7 on 2023-02-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_alter_song_decade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='chart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chart_images'),
        ),
    ]
